=== Hyanmo/XML/option2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="options" type="optionsType">
        <xsd:unique name="etudiantID">
            <xsd:selector xpath="etudiant"/>
            <xsd:field xpath="@numero"/>
        </xsd:unique>
        <xsd:key name="coursID">
            <xsd:selector xpath="cours"/>
            <xsd:field xpath="@id"/>
        </xsd:key>
        <xsd:keyref name="coursRef" refer="coursID">
            <xsd:selector xpath="etudiant/option"/>
            <xsd:field xpath="@cours"/>
        </xsd:keyref>
    </xsd:element>
    <xsd:complexType name="optionsType">
        <xsd:sequence>
            <xsd:element name="cours" type="coursType" minOccurs="1" maxOccurs="unbounded"/>
            <xsd:element name="etudiant" type="etudiantType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="coursType">
        <xsd:sequence>
            <xsd:element name="responsable" type="xsd:string" minOccurs="1" maxOccurs="2"/>
            <xsd:element name="descripition" type="descripitionType" maxOccurs="1"/>
            <xsd:element name="seance" type="seanceType" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="remarque" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>    
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="titre" type="xsd:string" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="descripitionType" mixed="true">
        <xsd:sequence>
            <xsd:element name="objectif" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="prerequis" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="seanceType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="no" type="xsd:integer" use="required"/>
                <xsd:attribute name="date" type="xsd:string" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:complexType name="etudiantType">
        <xsd:sequence>
            <xsd:element name="nom" type="xsd:string"/>
            <xsd:element name="option" type="optionType"/>
            <xsd:element name="absence" type="absenceType"/>
        </xsd:sequence>
        <xsd:attribute name="numero" type="xsd:string" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="optionType">
        <xsd:attribute name="cours" type="xsd:string" use="required"/>
        <xsd:attribute name="note" type="xsd:int" use="optional"/>
    </xsd:complexType>
    <xsd:complexType name="absenceType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="type" type="xsd:string" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
</xsd:schema>

=== Hyanmo/XML/option.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<options xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="option2.xsd">
    <cours id="c1" titre="XML">
        <responsable>D. Vodislav</responsable>
        <descripition>Ce cours permet de 
            <objectif>decouvrir le format XML</objectif>et
            <objectif>maistriser les langages lies a XML</objectif>
            . prerequis:<prerequis>JAVA</prerequis>et<prerequis>XML</prerequis>
        </descripition>
        <seance no="1" date="20/09/2019">Introduction</seance>
        <remarque>Enseignement en anglais</remarque>
    </cours>
    <cours id="c2" titre="Developing mobile applications">
        <responsable>D. Kotzinos</responsable>
        <descripition>...</descripition>
        <seance no="1" date="20/09/2019">Introduction</seance>
        <remarque>Enseignement en anglais</remarque>
    </cours>
    <etudiant numero="n123456">
        <nom>Philippe Dupont</nom>
        <option cours="c1" note="14"/>
        <absence type="justifiee">27/09/2019</absence>
    </etudiant>
</options>
